### PR TITLE
__precompile__() warnings fixed

### PR DESCRIPTION
**Pull request by ekyurdakul**
`__precompile__()` works properly now. #52

### CODE REVIEW

**Comment by denizyuret** [comment]
What was the problem with __precompile__() here?  The reason I added the eval's was to make things work on CPU only machines, I think.  Did you test this on a CPU only machine without nvidia libraries?

**Comment by ekyurdakul** [comment]
Using **precompile()** in a user defined module, which had `using Knet` would produce warnings. I didn't test it on a CPU only machine, since I thought on a CPU only machine, **ccall()** would throw an exception, which would be caught by the catch statement.

**Comment by denizyuret** [comment]
Can you send me an example of the warnings you get?  On a cpu only machine
I get (if I remove eval):

julia> using Knet
INFO: Recompiling stale cache file /Users/dyuret/.julia/lib/v0.5/Knet.ji
for module Knet.
ERROR: LoadError: error compiling __init__: error compiling gpu: error
compiling gpuCount: could not load library "libnvid$
dlopen(libnvidia-ml.dylib, 1): image not found
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at
/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at
/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at
/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/dyuret/.julia/v0.5/Knet/src/Knet.jl, in expression
starting on line 36
ERROR: Failed to precompile Knet to /Users/dyuret/.julia/lib/v0.5/Knet.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:393
 in require(::Symbol) at
/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?

**Comment by ekyurdakul** [comment]
This happens only with modules installed in Julia's package directory. Defining a new module outside this directory and using it doesn't result in this problem. On a GPU machine, I get the following:

With **eval()**:

> julia> using Tracking
INFO: Recompiling stale cache file /home/emre/.julia/lib/v0.5/Tracking.ji for module Tracking.
WARNING: eval from module Knet to Tracking:    
Expr(:||, Expr(:call, :==, Expr(:ccall, Expr(:tuple, "nvmlInit", "libnvidia-ml")::Any, :UInt32, Expr(:tuple)::Any)::Any, 0)::Any, Expr(:call, :error)::Any)::Any
  ** incremental compilation may be broken for this module **
WARNING: eval from module Knet to Tracking:    
Expr(:||, Expr(:call, :==, Expr(:ccall, Expr(:tuple, "nvmlDeviceGetCount", "libnvidia-ml")::Any, :UInt32, Expr(:tuple, Expr(:curly, :Ptr, :Cuint)::Any)::Any, Array{UInt32, 1}[0x00000000])::Any, 0)::Any, Expr(:call, :error)::Any)::Any
  ** incremental compilation may be broken for this module **
INFO: Knet using GPU 0

Without **eval()**:

> julia> using Tracking
INFO: Recompiling stale cache file /home/emre/.julia/lib/v0.5/Knet.ji for module Knet.
INFO: Knet using GPU 0
INFO: Recompiling stale cache file /home/emre/.julia/lib/v0.5/Tracking.ji for module Tracking.
INFO: Knet using GPU 0

**Comment by denizyuret** [comment]
Let me know if you can figure out a way to get rid of the warning without
breaking cpu-only machines.

**Comment by denizyuret** [comment]
I decided to add a new macro @cuda1, which silently returns nothing if the library cannot be found. Using @cuda1 during init removed the warnings. Calling shell commands etc. will add more risk of braking things on other systems.

**Pull request closed without merging**
