### PR TITLE
fix mnist data dependency, add Images package

### PR DESCRIPTION
**Pull request by ilkerkesen**
I did forget to add Images as dependency. Image resizing used in mnistgrid procedure, that's why it needs Images.

### CODE REVIEW

**Comment by denizyuret** [comment]
Should we generalize this as an image grid and add it to data/imagenet.jl ?  Advantages:
1. Loading mnist will be faster for people not interested in visualization (imagenet already needs Images.jl).
2. We can have a generic utility that can be used with mnist, cifar, imagenet data etc.

**Comment by ilkerkesen** [comment]
OK, but we need to fix hardcoded channel size.

**Comment by denizyuret** [comment]
We can get this from the particular input array can't we?  Also, don't you
need to use colorview to get an image output?

**Comment by ilkerkesen** [comment]
OK, I'll close this PR and I use colorview in plotting procedures. Sometimes I want to save the generations, I am not sure whether colorview breaks saving or not.

**Comment by denizyuret** [comment]
You don't have to use colorview, I just did not know you could display
stuff without converting with colorview...

**Pull request closed without merging**
