### PR TITLE
Port ilkarman benchmark examples to modular interface

### PR DESCRIPTION
**Pull request by ilkerkesen**
This PR ports two of ilkarman benchmark examples to new modular interface.

### CODE REVIEW

**Comment by denizyuret** [comment]
How is the performance compared to the master version or the 0.6 version?

**Comment by denizyuret** [comment]
TODO:
[ ] port all ilkarman benchmarks.
[ ] compare with Julia 0.6 Knet to see if any speed regression (assuming benchmarks are same).
[ ] compare with other frameworks and improve any shortcomings.

**Comment by ekinakyurek** [comment]
I can’t see that branch, could you point me?

**Comment by denizyuret** [comment]
Apparently I forgot to push, I did now, but you should probably use your
latest branch (called ilkarmanbenchmarks I assume) if it is up to date with
everything.

**Pull request closed without merging**
