### PR TITLE
Add CI for windows, freebsd, ARM

### PR DESCRIPTION
**Pull request by ianshmean**
The integrations may need to be enabled:
https://ci.appveyor.com
https://drone.io/
https://cirrus-ci.com/

Attempting to root out the problem in #489

### CODE REVIEW

**Comment by ianshmean** [comment]
@denizyuret it would be great if you could enable all the new CI integrations, listed above. I'm keen to get stability across all platforms

**Comment by ianshmean** [comment]
If you let me know when they're enabled, I can re-trigger by pushing to the branch

**Comment by denizyuret** [comment]
Thanks, just merged to master.

**Comment by denizyuret** [comment]
Hi Ian,

I merged the config files to master, and tried to activate on each
platform. Anything else I can do?

deniz

**Comment by denizyuret** [comment]
I looked at the first builds, the problems seem to be with CUDAapi not
being able to find the host_compiler. If the host_compilers do exist, we
should file an issue (and probably integrate these CIs with) CUDAapi.

**Comment by ianshmean** [comment]
Just taking a quick look at CUDAapi, it does look like the CI needs updating on Julia versions (Linux is 0.7 and windows is 1.0) and is missing arm and FreeBSD.

**Comment by denizyuret** [comment]
@maleadt may have a suggestion...

**Comment by ianshmean** [comment]
I've given it a go, over at https://github.com/JuliaGPU/CUDAapi.jl/pull/89

It's likely to be a bit of an explosion of CI time, but I think it's worth doing at least once to understand the scope of support

**Pull request merged**
