### PR TITLE
Broadcast

### PR DESCRIPTION
**Pull request by EnisBerk**
Cuda16 is buggy not working, Cuda17 allows broadcasting up to 10 dimension, this number can be increased by updating line 7 at cuda16.jl and 138 at broadcast/jl

### CODE REVIEW

**Comment by denizyuret** [comment]
I wrote a simple benchmarking script under Knet/prof/broadcast.jl. Here is the current output:
```
julia> include("../prof/broadcast.jl")
a[m,n].+b
        1       10      100     1000
1       7585    3820    3809    3865
10      3810    3863    3876    4125
100     3851    3870    4131    13152
1000    3877    4111    13602   89552
a[m,n].+b[1,n]
        1       10      100     1000
1       4864    3820    3814    3833
10      16982   16970   17189   17289
100     16946   16929   17560   27927
1000    16958   17230   24406   104057
a[m,n].+b[m,1]
        1       10      100     1000
1       4908    17064   17035   17160
10      3833    17046   17115   17157
100     3807    16993   17149   24511
1000    3860    17151   24654   107686
```

**Comment by ilkerkesen** [comment]
Especially in large array settings (e.g. ((513,1025),(1,1025)), we've got issues. Failing tests is obviously not related to CUDA kernels. These tests fail also with Julia arrays... Let me investigate them more to see if we've got a serious issue (56 failing tests currently).

**Comment by ilkerkesen** [comment]
We have two problems,

1. Some tests fail on both CPU and GPU arrays in large arrays.
2. On current master, we do not apply tests for max/min on CPU, but we perform those tests on GPU. Those tests fail also.

We need to uncomment the tests Enis has disabled. Then, we need to decide what to do with the first issue I've mentioned above.

**Comment by denizyuret** [comment]
Are these all gradcheck tests?

**Comment by ilkerkesen** [comment]
Yes, all of them are gradcheck tests.

**Pull request merged**
