### PR TITLE
Ilkarman benchmarks

### PR DESCRIPTION
**Pull request by ekinakyurek**
This is a PR that includes and follows #394 
It is a seperate PR because I couldn't push Ilker's PR since he created the branch in his own fork.

@Sophylax  could you check the notebook is working on a gpu machine ?

Best
Ekin

### CODE REVIEW

**Comment by denizyuret** [comment]
I had copied ilkers stuff on the ilkarman branch...

**Comment by ekinakyurek** [comment]
@denizyuret sorry for the duplicate branch. However, I can't see the branch that you mention. The latest commit in Knet.jl/ilkarman branch is in 2017.

**Comment by ekinakyurek** [comment]
Oh, that’s great @ilkerkesen, I was wondering how to do that. Could you pls
point me to a resource to find out how?

**Comment by ilkerkesen** [comment]
Just add the fork repository as a new remote. Fetch the new remote. Checkout new branch. Make your chances and then push to the PR branch/remote. Though, you need to be collaborator for the project. For instance,

```
git add remote ilker git@github.com:ilkerkesen/Knet.jl.git
git fetch ilker
git checkout -b ilkarman-modular ilker/ilkarman-modular
# do your changes
git push ilker ilkarman-modular
```

**Pull request closed without merging**
