### PR TITLE
fix serialize bug in #344

### PR DESCRIPTION
**Pull request by ekinakyurek**
After Julia fixed deepcopy bug, I fix our serialization bug too.

### CODE REVIEW

**Comment by denizyuret** [comment]
#425 ve #433 icin simdi fail eden duzeltmeden sonra gecen test lazim...

**Comment by ekinakyurek** [comment]
I merged with #425 and added the tests that fails before

**Comment by ekinakyurek** [comment]
@denizyuret could you try below by activating this project https://github.com/ekinakyurek/Morse.jl/tree/predict on a cpu only machine, which requires internet connection to download the saved model:

```JULIA
julia> using Knet, KnetLayers , Morse
julia> model, vocabulary, parser = trained(MorseModel, TRDataSet, vers="2018");
julia> predictions = model("annem sana yardım edemez .", v=vocabulary, p=parser)
```

I'm getting assertion error on size of hidden states, whereas I don't get any error on a GPU machine.

**Comment by denizyuret** [comment]
> ```julia
> ```julia
> julia> using Knet, KnetLayers , Morse
> julia> model, vocabulary, parser = trained(MorseModel, TRDataSet, vers="2018");
> julia> predictions = model("annem sana yardım edemez .", v=vocabulary, p=parser)
> ```
> ```

You had a 2-D hidden state instead of 3-D. I modified the code so the assertion ignores trailing 1 dimensions.

**Pull request merged**
